---
name: 'deploy to sjdonado.de'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@sjdonado.de:22/remix-dashboard'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
